### ISSUE TITLE
[Bug] Relogging a different user wont listen to socket messages through the handler

### ISSUE THREAD

**Issue by icodelifee** [team-telnyx/flutter-voice-sdk#23]
**Bug Category**
- [x] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [ ] Other

**SDK Version**
Which version of the SDK have you added from pub.dev? Feel free to add the whole dependency implementation:
eg. telnyx_webrtc: ^0.0.1

**Describe the bug**
When i open the app the Telnyx client gets connected and then i login to the client and observer the responses through the onSocketMessageReceived handler, when i logout the user [App user] and logs in with a different user i connect again, when i do this then i repeat the first step again and observe the response. After that no socket message gets handled by the callback

**Expected behaviour**

**To Reproduce**
Steps to reproduce the behaviour:
1. e.g. (Log on with credentials)
2. e.g. (Socket error then returned)

** Device (please complete the following information):**
- Emulator: (true/false)
- Device/Browser: [e.g. Pixel 6, iPhone XR, Chrome]
- OS Version: [e.g. Android Oreo,  iOS 12, Chrome Version 103.0.5060.53]

**Logs**
Please provide any logs available to you, remember to enable verbose logging within the SDK.

**Comment by Oliver-Zimmerman** [comment]
Hey @icodelifee 

Are you using 0.0.9? This issue should be resolved in that. Please test the sample application - I double checked then before making the release. 

If you can reproduce on the sample application please let me know

**Comment by icodelifee** [comment]
> Hey @icodelifee
> 
> Are you using 0.0.9? This issue should be resolved in that. Please test the sample application - I double checked then before making the release.
> 
> If you can reproduce on the sample application please let me know

i can check the sample app, would it be better that i send a loom video of my application to show you whats happening?

**Comment by icodelifee** [comment]
> > Hey @icodelifee
> > Are you using 0.0.9? This issue should be resolved in that. Please test the sample application - I double checked then before making the release.
> > If you can reproduce on the sample application please let me know
> 
> i can check the sample app, would it be better that i send a loom video of my application to show you whats happening?

and yes im using latest 0.0.9

**Comment by Oliver-Zimmerman** [comment]
> > Hey @icodelifee
> > Are you using 0.0.9? This issue should be resolved in that. Please test the sample application - I double checked then before making the release.
> > If you can reproduce on the sample application please let me know
> 
> i can check the sample app, would it be better that i send a loom video of my application to show you whats happening?

It would probably be better to be able to look at the code. Are you doing `notifyListeners();` on disconnect?

**Comment by icodelifee** [comment]
> > > Hey @icodelifee
> > > Are you using 0.0.9? This issue should be resolved in that. Please test the sample application - I double checked then before making the release.
> > > If you can reproduce on the sample application please let me know
> > 
> > 
> > i can check the sample app, would it be better that i send a loom video of my application to show you whats happening?
> 
> It would probably be better to be able to look at the code. Are you doing `notifyListeners();` on disconnect?

Im using statenotifiers from riverpod and on log out im not using the disconnect method in telnyx client
 State notifier code: https://katb.in/inowohoqodo

**Comment by Oliver-Zimmerman** [comment]
Since 0.0.9 the disconnect should work as expected. Can you try implement that quickly to see if it makes a difference? You can use the sample app as a guide.

**Comment by icodelifee** [comment]
> Since 0.0.9 the disconnect should work as expected. Can you try implement that quickly to see if it makes a difference? You can use the sample app as a guide.

I dont know what was causing the issue, not able to reproduce it now
