### ISSUE TITLE
 telnyxClient.call.newInvite(  _localName,  "+123456789",  destination,   "Fake State",  );     IS NOT WORK

### ISSUE THREAD

**Issue by lavishmanghnani2** [team-telnyx/flutter-voice-sdk#58]
**Bug Category**
- [x] Credential Login
- [ ] Token Login
- [ ] Local Audio Issue
- [ ] Remote Audio Issue
- [ ] Audio Device Switching
- [ ] Mute / Unmute
- [ ] Hold / Unhold
- [ ] Performance issues
- [x] Other

**SDK Version**
Which version of the SDK have you added from pub.dev? Feel free to add the whole dependency implementation:
eg. telnyx_webrtc: ^0.0.1

**Describe the bug**

**Expected behaviour**

**To Reproduce**
Steps to reproduce the behaviour:
1. e.g. (Log on with credentials)
2. e.g. (Socket error then returned)

** Device (please complete the following information):**
- Emulator: (true/false)
- Device/Browser: [e.g. Pixel 6, iPhone XR, Chrome]
- OS Version: [e.g. Android Oreo,  iOS 12, Chrome Version 103.0.5060.53]

**Logs**
Please provide any logs available to you, remember to enable verbose logging within the SDK.

**Comment by cmendes0101** [comment]
You need to provide more information to help
